displayName=Frieza Nex Plugin
author=muddygames
description=A plugin for Nex to sound like frieza with quotes from the show!
tags=Nex, nex
version=1.0.0
plugins=com.example.FriezaNexPlugin
build=standard